### ISSUE TITLE
Data Extraction Error

### ISSUE THREAD

**Issue by MilindRCodes** [Hussain-Alsalman/tasi#1]
Hi,

I am facing data extraction error. 
Can you please check the issue here. 

> # Performance of Saudi Aramco company stock 
> comp_df <- get_company_records("2022-07-01","2022-12-17",company_symbol = 2222, use_cache = FALSE)
Error in rjson::fromJSON(file = parseURL(0, startDate, endDate, type = type,  : 
  not all data was parsed (0 chars were parsed out of a total of 708542 chars)

> traceback()
4: stop(sprintf("not all data was parsed (%d chars were parsed out of a total of %d chars)", 
       size, nchar(json_str, type = "bytes")))
3: rjson::fromJSON(file = parseURL(0, startDate, endDate, type = type, 
       comSymbol = company_symbol, adjustment = adjustPeriod))
2: request_data(startDate = start_date, endDate = end_date, type = "company", 
       company_symbol = company_symbol, adjustPeriod = FALSE)
1: get_company_records("2022-07-01", "2022-12-17", company_symbol = 2222, 
       use_cache = FALSE)

**Comment by Abo7atm** [comment]
This is happening after Tadawul updated their website. I'm guessing that some links that were used to extract data aren't accessible anymore.

**Comment by MilindRCodes** [comment]
Hi,

Thank you for your quick revert.
Are you planning to update this project for the broken links anytime soon?

Would really appreciate if you can take a look.
Thank you.

**Comment by Abo7atm** [comment]
I'm not the author of this project, and honestly I don't even know where to start to fix this.

And just a small tip, since this service is not widely known, Tadawul (Saudi Exchange) offer a data service that is relatively cheap and super easy to use. Although it's not an API that you can integrate with, they offer all historical data in tabular form. You can find this service by searching for "eReference Data Tadawul".

There's also [yfinance](https://github.com/ranaroussi/yfinance), where you can lookup companies in the Saudi market by suffixing the symbol with `.SR`, so Aramco would be `2222.SR`. 

Hopefully Hussain can fix the current issue and we can go back to using this great project. 

Cheers.

**Comment by Hussain-Alsalman** [comment]
@MilindRCodes Thanks for bringing this to my attention. 

@Abo7atm is right. This is happening due to the recent Tadawul website overhaul. All asynchronous calls have changed making `parseURL` function producing obsolete broken urls. 

Moreover, I have to check all other functions as well. This might call for major update of the `tasi` package.  I will give it a shot once I have some free time. Meanwhile, I second @Abo7atm for his suggested alternatives.     

**CAUTION**: Please exercise caution while using  [Yahoo! Finance's](https://finance.yahoo.com/) especially if you are relying on _adjusted_ prices in your financial analysis. It incorrectly incorporates dividend and splits.

**Comment by Hussain-Alsalman** [comment]
It is working now, 

cheers!
